name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: jorelali/setup-elm@v1
        with:
          elm-version: 0.19.1
      - run: elm make src/Main.elm --output=dist/app.js
